# BEC-CONFIG 1
baseUrl	下载服务地址	"https://raw.githubusercontent.com/"
repository	GitHub仓库	"Misaka2592/becAutomation"
branch	下载分支	"experiment-configuration"
destination	默认安装目录	"/home"
files	下载文件	{ "setup.conf", "bec.conf", "bec_config.lua", "bec_automation.lua", "bec_automation_config.lua", "bec_component_resolver.lua", "bec_counter.lua", "bec_dashboard.lua", "bec_diagnostics.lua", "bec_field_strength.lua", "bec_fluid_routes.lua", "bec_fluid_routes.conf", "bec_nanite_transfer.lua", "bec_route_mapper.lua", "bec_route_mapper_config.lua", "bec_config_edit.lua", "bec_config_edit.py" }

